### ISSUE TITLE
How to do OBS streaming & Could The HUD change font

### ISSUE THREAD

**Issue by eeveecsgo** [drweissbrot/csgo-hud#25]
How to do OBS streaming & Could The HUD change font
that all my question thank you,
btw i noob in Computer Maybe i may ask stupid question
About OBS streaming the problem is If i steam the Hud on the front cover is it Black BACK GROUND,I Cant deal with streaming the whole screen that all thank you!!

**Comment by drweissbrot** [comment]
re changing the font:
no plans to make it easily customizable, but you could change `Source Sans Pro` here to the font you want to use -- just make sure the font is installed on your PC
https://github.com/drweissbrot/csgo-hud/blob/d031c8e968616f9ddd3161843065ebfc9a3cd67f/src/stylus/base.styl#L15-L16


re OBS:
not sure if i understand your question -- my usage of this was always to have the HUD visible on top of the game (i believe you have to run CS:GO in Fullscreen Windowed for that to work), and then just record with a Display Capture in OBS
it might be possible to capture the HUD separately from the game, and then use a Chroma Key or maybe Luma Key filter to get rid of the background, but i'd expect that to look pretty bad for all the semi-transparent parts of the HUD

**Comment by eeveecsgo** [comment]
> re changing the font: no plans to make it easily customizable, but you could change `Source Sans Pro` here to the font you want to use -- just make sure the font is installed on your PC
> 
> https://github.com/drweissbrot/csgo-hud/blob/d031c8e968616f9ddd3161843065ebfc9a3cd67f/src/stylus/base.styl#L15-L16
> 
> re OBS: not sure if i understand your question -- my usage of this was always to have the HUD visible on top of the game (i believe you have to run CS:GO in Fullscreen Windowed for that to work), and then just record with a Display Capture in OBS it might be possible to capture the HUD separately from the game, and then use a Chroma Key or maybe Luma Key filter to get rid of the background, but i'd expect that to look pretty bad for all the semi-transparent parts of the HUD
thank you to helping me :))
