### ISSUE TITLE
Scoreboard background doesnt extend enough

### ISSUE THREAD

**Issue by bonocs** [drweissbrot/csgo-hud#32]
![Screenshot (15)](https://user-images.githubusercontent.com/76176911/152048457-852324f0-281b-423f-a815-70c0df2aead5.png)

There seems to be a gap between where the background color of the scoreboard ends and the slanted line starts, it also looks like the scoreboard might be smaller than in your screenshot (cant confirm this)

I'm running at 4k if that helps at all

**Comment by drweissbrot** [comment]
Not sure if this will fix it, but could you try installing the font, Quantico? e.g. from https://fonts.google.com/specimen/Quantico

**Comment by bonocs** [comment]
That fixed it, Thanks!

**Comment by bonocs** [comment]
Forgot to mention this but is the colored K/D supposed to be gone in the newest version?
