### ISSUE TITLE
Timeout Timer Bar doesn't decrease until timeout time is <= 25 seconds

### ISSUE THREAD

**Issue by bonocs** [drweissbrot/csgo-hud#33]
Hey, it's me again. The timeout bar stays full until there's 25 seconds left in the timeout. I tried to get around this by just changing the timeout time to 25 seconds which did fix the issue but the teams in my league were complaining that the timeouts are too short. I'm not sure if this is intended behavior but if you could make it work with timeouts longer than 25 seconds that would be great.

I was also wondering if there is any way to play the post match background video without the animation showing, just the video. I read through your documentation and couldn't find anything.

**Comment by drweissbrot** [comment]
Can't quite reproduce this. The duration is hardcoded as 30 seconds as the duration isn't provided by game state integration (feel free to submit a PR to make it configurable).

If your timeouts are longer than 30 seconds, it's probably easiest if you changed the value here: https://github.com/drweissbrot/csgo-hud/blob/cb08150fbae2a66d79ddfb58c36846abba01f28b/src/renderer/Components/Timeout.vue#L111

If your timeouts are 30 seconds, did this happen while watching a demo, GOTV, or as a Spectator in a live match? Could you provide a demo where this happened?

**Comment by bonocs** [comment]
> Can't quite reproduce this. The duration is hardcoded as 30 seconds as the duration isn't provided by game state integration (feel free to submit a PR to make it configurable).
Not exactly sure what you mean by this, if you mean that you can't change the timeout time in game, there is a command called mp_team_timeout_time which adjusts the duration of timeouts. If that's not what you meant please rephrase.

> If your timeouts are 30 seconds, did this happen while watching a demo, GOTV, or as a Spectator in a live match? Could you provide a demo where this happened?
This happened in a live match, unfortunately I didn't record the demo for that match so I cant provide it. I'll try reproducing it later today and then I can provide the demo. Timeout duration was also set to 60 seconds but the bar wouldn't start moving until the in game clock was at 25 seconds remaining.

I tried changing the value in the script you provided, I have my timeouts at 90 seconds so I adjusted the value accordingly but now there's two problems

1. The in game clock doesn't match up with the timeout duration
2. The bar still doesn't move

![Screenshot (26)](https://user-images.githubusercontent.com/76176911/152255481-a5b74103-5b3c-4022-8eb5-a90e154a49ad.png)

**Comment by drweissbrot** [comment]
Sorry, my mistake :D The duration is set to 30 seconds in the HUD's code, because the game doesn't tell the HUD how long timeouts are.

> The in game clock doesn't match up with the timeout duration

From my testing, this only happens in timeouts (correct me if I'm wrong) and the difference is only 1 second, so I don't feel it's that big a deal. I don't think anyone would really notice without seeing the ingame timer alongside the HUD.

**Comment by bonocs** [comment]
> From my testing, this only happens in timeouts (correct me if I'm wrong) and the difference is only 1 second, so I don't feel it's that big a deal. I don't think anyone would really notice without seeing the in game timer alongside the HUD.
>
The screenshot from my last reply was with 60 second timeouts, and an extra minute somehow got added. I reinstalled your HUD and that fixed the timer issue, but even after altering the HUD's code as you suggested the bar still doesn't move.

I tried recording a demo by doing:
>
record (name)
stop
>
But when I checked the replays folder it was not there, did I do something wrong?

**Comment by bonocs** [comment]
I'm also not able to change the tactical timeout music, I had it set as the ESL version but when I tried changing it to the Blast version it would work, but even after pressing save the next launch of the HUD would have the ESL version again.

**Comment by drweissbrot** [comment]
> But when I checked the replays folder it was not there, did I do something wrong?

I believe recorded demos are saved in the `csgo` directory, not within `replays`, i.e. `steamapps/Counter-Strike Global Offensive/csgo` directly.

**Comment by bonocs** [comment]
> I believe recorded demos are saved in the `csgo` directory, not within `replays`, i.e. `steamapps/Counter-Strike Global Offensive/csgo` directly.

Yep, found it however GitHub doesn't let me send it. Do you have anything else I can try that doesn't require me sending a demo?

**Comment by bonocs** [comment]
this.remainingTime = Math.max(0, Math.min(1, now.phase_ends_in / 60))

This is the line you asked me to edit but it doesn't seem to control any of the UI elements, unless I have to use yarn to create a new executable?

**Comment by drweissbrot** [comment]
> This is the line you asked me to edit but it doesn't seem to control any of the UI elements, unless I have to use yarn to create a new executable?

My mistake again, I just assumed you were using `yarn start`. If you're using `yarn build` or `yarn package`, yes, you have to do that again (and also run the installer again if you're using `build`).

**Comment by bonocs** [comment]
That fixed it!

Do you know what could cause this?

> I'm also not able to change the tactical timeout music, I had it set as the ESL version but when I tried changing it to the Blast version it would work, but even after pressing save the next launch of the HUD would have the ESL version again.

**Comment by drweissbrot** [comment]
> I'm also not able to change the tactical timeout music, I had it set as the ESL version but when I tried changing it to the Blast version it would work, but even after pressing save the next launch of the HUD would have the ESL version again.

Try hitting save a couple of times, maybe it just didn't go through for some reason.
Also keep in mind that if you select multiple files, it'll pick one at random each timeout.

**Comment by bonocs** [comment]
Where are the timeout files stored? Whenever I overwrite the file it doesn't show both files, only the newer one.

**Comment by drweissbrot** [comment]
The HUD doesn't store the audio files anywhere, it just takes the files you selected. You can select multiple files (as long as they're in the same directory) by holding Ctrl or Shift while selecting them.

**Comment by bonocs** [comment]
Got it, one last thing

> I was also wondering if there is any way to play the post match background video without the animation showing, just the video. I read through your documentation and couldn't find anything.

Is this possible currently or is it easier to just edit the post match video into the recording?

**Comment by drweissbrot** [comment]
Probably easiest to just edit it in.

**Comment by bonocs** [comment]
Alright.

You're amazing dude. 
The fact that you make something this high quality for free is honestly shocking, I don't have words to describe how talented you are.
