### ISSUE TITLE
gamestate integration

### ISSUE THREAD

**Issue by bonocs** [drweissbrot/csgo-hud#35]
Back again, seems like your gamestate integration doesn't capture the `Win Chance` (this bar is found in the default HUD under the round timer, not present in your version.) Either that or I just can't figure out how to display it.

**Comment by drweissbrot** [comment]
I don't think that Game State Integration provides that data.

**Comment by bonocs** [comment]
Alright, do you have any ideas on how `Blast` and some tier two events do it then?
![image](https://user-images.githubusercontent.com/76176911/156015405-4e91a6b6-3265-46cc-acd3-4525476e6dfc.png)

**Comment by bonocs** [comment]
Found a slightly different version
`"Observer All Players v.1"
{
 "uri" "http://10.0.1.3:8080"
 "timeout" "5.0"
 "buffer"  "0.1"
 "throttle" "0.1"
 "heartbeat" "30.0"
 "auth"
 {
   "token" "Q79v5tcxVQ8u"
 }
 "data"
 {
   "provider"            "1"
   "map"                 "1"
   "round"               "1"
   "player_id"           "1"
   "allplayers_id"       "1"      // Same as 'player_id' but for all players. 'allplayers' versions are only valid for HLTV and observers
   "player_state"        "1"      
   "allplayers_state"    "1"      
   "allplayers_match_stats"  "1"  
   "allplayers_weapons"  "1"      
   "allplayers_position" "1"      // output the player world positions, only valid for GOTV or spectators. 
   "phase_countdowns"    "1"      // countdowns of each second remaining for game phases, eg round time left, time until bomb explode, freezetime. Only valid for GOTV or spectators. 
   "allgrenades"    "1"           // output information about all grenades and inferno flames in the world, only valid for GOTV or spectators.
 }
}`
But still doesn't seem to include anything useful, do you think trying to calculate based on equipment is the best strategy?

**Comment by drweissbrot** [comment]
Well I personally think not including this at all is best (it distracts from the game, HUDs in general are already pretty cluttered, and if it's wrong it doesn't add any value, and if it's right it spoils the result of the round) -- but you do you.

I'd assume the easiest and least prone to breaking way would again be to just use equipment value. Would also make sense with Blast's "Firepower" label.
Anything more elaborate I can't say anything about, you'd need to ask a data scientist about that :D

**Comment by bonocs** [comment]
Alright, I'll try that. Thanks for your help!
