### ISSUE TITLE
Team renaming

### ISSUE THREAD

**Issue by Simber1** [drweissbrot/csgo-hud#36]
It would be nice if there was support for renaming the team names from CT and T to something custom.

**Comment by drweissbrot** [comment]
The game supports this with by setting the `mp_teamname_1` and `mp_teamname_2` cvars on the game server, or by having everyone join a Steam group and selecting that group as their clan tag.
Would either of these work for your use case?

**Comment by Simber1** [comment]
Unfortunately not, It's for a UK Uni league and the plugin/backend they use for setting up the servers don't input the teamnames automatically and it's uni students so they don't use Steam groups, getting uni students to do anything is impossible.
