### ISSUE TITLE
Problem with CSS

### ISSUE THREAD

**Issue by XIIIG** [drweissbrot/csgo-hud#42]
Not sure why, but CSS doesn't work when I run HUD from exe file, it works fine when using yarn start.

https://i.imgur.com/J95p6RI.png
https://i.imgur.com/D8JSHGf.png

I'm using windows 11.

**Comment by Simber1** [comment]
Yeah I'm not sure what causes it, I got the same issue the second time I launched it. Worked fine the first time.

**Comment by drweissbrot** [comment]
Are you using a plain EXE file or an installer (i.e. `yarn package` or `yarn build`)?
Also, could you open the dev tools (`Ctrl+Shift+I`) in the config window, go to the Console tab, and see if there's anything in there?

**Comment by XIIIG** [comment]
Just tested it again.

It works fine when I use `yarn package`.
`yarn build` seems to be broken, here is the log from the dev tools:

https://i.imgur.com/HRdFyPg.png

**Comment by drweissbrot** [comment]
Could you clone this branch and see if it's fixed there? https://github.com/drweissbrot/csgo-hud/tree/fix-42-build-css

**Comment by Simber1** [comment]
> Could you clone this branch and see if it's fixed there? https://github.com/drweissbrot/csgo-hud/tree/fix-42-build-css

That fix works for me.

**Comment by XIIIG** [comment]
It fixed the issue, thank you.
