### ISSUE TITLE
Move map images into repository

### ISSUE THREAD

**Issue by drweissbrot** [drweissbrot/csgo-hud#50]
Map images are currently loaded from csgo.drweissbrot.net (cf. https://github.com/drweissbrot/csgo-hud/blob/cb08150fbae2a66d79ddfb58c36846abba01f28b/src/stylus/series-map.styl), which is being killed. These images (and probably those for all missing maps) should be added to this repository.

**Comment by 42Firehawk** [comment]
while there are other significant changes that have been made within the fork (colour changes, a few workshop maps added, etc) the csconfederation fork does now have local map image loading that is functional (though perhaps not using the cleanest method). 
https://github.com/csconfederation/csgo-hud for the fork referred to

**Comment by drweissbrot** [comment]
closing this as it's been handled for v2 in fdd7af6c81f9aecca3126786aa61f6cabca134b2
