### ISSUE TITLE
Team Logos, players photos

### ISSUE THREAD

**Issue by everestgear** [drweissbrot/csgo-hud#51]
Hi. Is it possible to add such function as add Team and Players where i can upload Team Logo, and in Add Player to upload a player photo? 
Also can you give me advise how to make it possible to use your HUD as web page as it has boltobserver radar (36363) or custom hud( port :2626). 
Thanks for you HUD. Its great!

**Comment by drweissbrot** [comment]
> upload Team Logo, and […] player photo?

I'm not interested in adding either of these as features for now, sorry.
Team logos you could probably get to work somewhat easily by replacing the flags, e.g. in https://github.com/drweissbrot/csgo-hud/blob/6bee48967f6a94181315ba3c86de1eeebe42f304/src/renderer/Components/TopBar.vue#L27 Player avatars would be more difficult.

You could also look into alternative projects that have support for this, maybe https://github.com/lexogrine/hud-manager.

> use your HUD as web page

Not a thing either, for the time being at least.
