### ISSUE TITLE
v2: Config page

### ISSUE THREAD

**Issue by drweissbrot** [drweissbrot/csgo-hud#54]
A separate web page, accessible at http://hud.example/config. Similar to the old "config window".

Should show an input to change the used theme, and inputs for all options provided by that theme and its parent themes.

Changes should be saved via a dedicated button (so that typing something in mid-broadcast isn't visible on stream), and `Ctrl+S`. Changes should be saved to `userspace/theme.json`.  
Immedately after saving, the settings should be re-indexed and broadcast via websockets.

Changing the theme (and saving) should trigger a refresh of all HUD instances. There should also be a button to trigger a reload (e.g. for when developing themes).

~~The radar should also be embedded on this page.~~ (moved to #63)

**Comment by aL1NaZ4R** [comment]
**Idea:** having some simple theme settings will be good. (Like T/CT Color, Fonts, etc.)
