### ISSUE TITLE
v2: Crosshair overlay

### ISSUE THREAD

**Issue by drweissbrot** [drweissbrot/csgo-hud#58]
Heard of a bug in CS:GO where the crosshair disappears. That's not technically something for the HUD, but if Valve won't fix it, someone has to :D  
This may also solve itself with CS2.

Can probably do this by overlaying a crosshair SVG (or a configurable DOM element) on the screen.

Should either be on-hotkey or via theme option.  
Needs special consideration for AWP, Scout, SCAR, G3SG1, and very special consideration for AUG and SG553.

**Comment by 42Firehawk** [comment]
As a note: this is known fixed in CS2, and occurs when a weapon is dropped to someone else, the person the weapon is dropped to won't show a crosshair to observers.

**Comment by drweissbrot** [comment]
Will trust you on this one and not go ahead with it :+1: Thanks!
