### ISSUE TITLE
GUI Shows on wrong screen.

### ISSUE THREAD

**Issue by NintyS** [drweissbrot/csgo-hud#71]
Yo, I testing this on Linux and everything works well except that I have UI on the other screen than this where CS:GO is. WHat I can do with it?

**Comment by 42Firehawk** [comment]
Hey Ninty, when I have the problem within windows I just use the hotkey to change monitors (shift+super+arrow key) and it changes which monitor the transparent gui window is on. Just make sure to manually select the window first.

**Comment by drweissbrot** [comment]
Yeah, works exactly the same on Linux, at least on Ubuntu with Gnome. You may need to select the window with Alt+Tab, or by selecting it in the task bar, it does behave a bit erratically sometimes :D

Feel free to reopen if this doesn't solve your issue :)
