### ISSUE TITLE
Change text in end round boxes.

### ISSUE THREAD

**Issue by NintyS** [drweissbrot/csgo-hud#72]
Yo, I wanna ask from where program is taking for e.g "Win  the round by Eliminating the Enemy Team"? I wonder if I can translate overlay.

**Comment by drweissbrot** [comment]
They're here: https://github.com/drweissbrot/csgo-hud/blob/6bee48967f6a94181315ba3c86de1eeebe42f304/src/renderer/Components/RoundWinner.vue#L80-L83

If you completely want to hide these, just delete these lines entirely. If you want to translate them, just replace the strings with your translation :D
